services:
# infra containers
  postgres:
    container_name: postgres
    image: postgres:16.9
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/dataset.csv:/docker-entrypoint-initdb.d/dataset.csv:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - insurance-network

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - insurance-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - insurance-network

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKER_CONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - zookeeper
      - kafka

    networks:
      - insurance-network

### APP SERVICES ###
  gateway-service:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - auth-service
      - customer-service
      - policy-service
      - payment-service
      - claim-service
      - underwriting-service
    networks:
      - insurance-network

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - insurance-network

  customer-service:
    build:
      context: ../customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - insurance-network

  policy-service:
    build:
      context: ../policy-service
      dockerfile: Dockerfile
    container_name: policy-service
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - insurance-network

  payment-service:
    build:
      context: ../payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - insurance-network

  claim-service:
    build:
      context: ../claim-service
      dockerfile: Dockerfile
    container_name: claim-service
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - insurance-network

  underwriting-service:
    build:
      context: ../underwriting-service
      dockerfile: Dockerfile
    container_name: underwriting-service
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - insurance-network


volumes:
  postgres-data:

networks:
  insurance-network:
    driver: bridge
